### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by aagp** [overtrue/laravel-favorite#1]
Hi, i was trying to install your package, in Laravel 5.8 but when i try

`composer require overtrue/laravel-favorite -vvv`

the following error appears:

```
[InvalidArgumentException]
Could not find package overtrue/laravel-favorite at any version for your minimum-stability (dev). Check the package spelling or your minimum-stability
```

Any work around?
Regards

**Comment by overtrue** [comment]
Sorry, I'v forgot to release it. Plz try again later.
