### ISSUE TITLE
Its giving exception

### ISSUE THREAD

**Issue by ersanyakit** [overtrue/laravel-favorite#10]
Symfony\Component\Debug\Exception\FatalThrowableError
syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ',' or ')'

    public function getFavoriteItems(string $model)

    {

        return app($model)->whereHas(

            'favoriters',

            **fn ($q) => $q->where(config('favorite.user_foreign_key'), $this->getKey())**

        );

    }

**Comment by overtrue** [comment]
Please upgrade to the latest version to fix it.  https://github.com/overtrue/laravel-favorite/releases/tag/2.1.2

<blockquote><img src="https://avatars1.githubusercontent.com/u/1472352?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/overtrue/laravel-favorite">overtrue/laravel-favorite</a></strong></div><div>:heart: User favorite feature for Laravel Application. - overtrue/laravel-favorite</div></blockquote>
