### ISSUE TITLE
Unable to locate publishable resources.

### ISSUE THREAD

**Issue by Xodus-CO** [overtrue/laravel-favorite#12]
Receive the following error when trying to publish migration files or config files on Laravel 8.

```
php artisan vendor:publish --provider="Overtrue\\LaravelFavorite\\FavoriteServiceProvider" --tag=migrations
Unable to locate publishable resources.
Publishing complete.
```

Was able to manually copy package vendor config/favorite.php to app/config/favorite.php

**Comment by uptutu** [comment]
If you are using a Windows PC, try `php artisan vendor:publish `and select the corresponding tag.

Or executed following set of commands:
```bash
php artisan clear-compiled
composer dumpautoload
```
After that try `php artisan vendor:publish --provider="Overtrue\LaravelFavorite\FavoriteServiceProvider" `

**Comment by Xodus-CO** [comment]
> 
> 
> If you are using a Windows PC, try `php artisan vendor:publish `and select the corresponding tag.
> 
> Or executed following set of commands:
> 
> ```shell
> php artisan clear-compiled
> composer dumpautoload
> ```
> 
> After that try `php artisan vendor:publish --provider="Overtrue\LaravelFavorite\FavoriteServiceProvider" `

The clear-compiled, dumpautoload and re-running the publish worked, except now I get errors about missing class.
```
Class 'Database\Factories\Overtrue\LaravelFavorite\FavoriteFactory' not found
```

**Comment by Xodus-CO** [comment]
Resolved the FavoriteFactory issue by editing config/favorite.php.

```
 'favorite_model' => 'App\Models\Favorite',
```
