### ISSUE TITLE
Only allow Logged-In users to Favorite. Collections of favorites.

### ISSUE THREAD

**Issue by oliveflow** [overtrue/laravel-favorite#16]
Hi there,
I want to know that, how can I allow only users that are logged in to favorite and if the user is not logged in it will prompt an error??. So please help me.

And also please tell me if this package has support for collection of favorites. If not and you think of adding it, can you please let me know the estimated time for that upgrade. Hope to see it soon.

By the way, It's a great package overall.

**Comment by yaroswell** [comment]
You can use auth middleware to deny access to favorite routes for users which are not logged in.
