### ISSUE TITLE
Favorite() keeps creating new records in the database.

### ISSUE THREAD

**Issue by PitchRE** [overtrue/laravel-favorite#18]
When using favorite() on model, it keeps creating records in the table.
hasFavorited() fails to find anything.

>  $user->favorite(Item::find(1));

>  "overtrue/laravel-favorite": "^4.0",

**Comment by overtrue** [comment]
Please paste the context code, thanks.

**Comment by PitchRE** [comment]
no context code. just closure on web route.
notes; i did not publish config file, maybe its related to it?
I copies methods I was interested in and replaced config references with static stuff and it works so yeah.
tested on fresh laravel project.

**Comment by overtrue** [comment]
Sorry I really can't reproduce your problem, if you modified the code by yourself or didn't install it according to README, you may need to check what the problem is, sorry.

**Comment by PitchRE** [comment]
I did not modified the code. I had to do that in order to make it correctly.
Ill try to reproduce this issue this week.

**Comment by loureirorg** [comment]
@PitchRE To help with the debug, you can enable to show SQL queries on Tinker. Then, you can see what is happening on the database:

1. Open Tinker on your terminal:
```bash
php artisan tinker --ansi
```

2. Enable to show SQL:
```php
DB::listen(function ($query) {
    dump("[{$query->time}ms] {$query->sql}");
    if ($query->bindings) {
        dump($query->bindings);
    }
});
``` 

Now, any access to the database will be shown on your screen:
```php
$user = User::find(2);
//"[2.1ms] select * from `users` where `users`.`id` = ? and `users`.`deleted_at` is null limit 1"
//array:1 [
//  0 => 2
//]
```

It may be helpful to publish the SQL queries when you run multiple times:
```php
$user->favorite(Item::find(1));
```
