### ISSUE TITLE
Can't publish migrations unless I use `--tag=favorite-migrations`

### ISSUE THREAD

**Issue by loureirorg** [overtrue/laravel-favorite#19]
* Version: 4.0.1
 
I tried to publish the migrations according to README:
```bash
php artisan vendor:publish --provider="Overtrue\\LaravelFavorite\\FavoriteServiceProvider" --tag=migrations
```
But it didn't work, I got this message:
```
No publishable resources for tag [migrations]
```

And of course, the migration files weren't published.

---

To fix it, I replaced "_migrations_" with "_**favorite-migrations**_":
```bash
php artisan vendor:publish --provider="Overtrue\\LaravelFavorite\\FavoriteServiceProvider" --tag=favorite-migrations
```
And that worked.

The same issue happens when publishing the configuration file: `--tag=config` vs `--tag=favorite-config`. 

Also, this issue is preventing the library from working out of the box. After installing it and refreshing the migrations, I got an `1146 Table 'favorites' doesn't exist` SQL error. 

But forcing the migration files with "favorite-migrations" fixed the issue (it generated the `favorites` table).

**Comment by overtrue** [comment]
@loureirorg Thanks for your feedback, I've updated the docs.

**Comment by MuhammedAlkhudiry** [comment]
same with config it should be 
```
php artisan vendor:publish --provider="Overtrue\\LaravelFavorite\\FavoriteServiceProvider" --tag=favorite-config
```
