### ISSUE TITLE
Call to a member function toggleFavorite() on null

### ISSUE THREAD

**Issue by the-Tofiq** [overtrue/laravel-favorite#22]
i have favoriter user and favoriteable vacancy. When I try to save, I get this error (Call to a member function toggleFavorite() on null).
$vacancy = Vacancy::where('slug',$slug)->firstOrFail();
$response = auth()->user()->toggleFavorite($vacancy);

**Comment by overtrue** [comment]
```
auth()->user() // user doesn't login ...
```
