### ISSUE TITLE
Return value must be of type Illuminate\Database\Query\Builder

### ISSUE THREAD

**Issue by klaasnicolaas** [overtrue/laravel-favorite#26]
![image](https://user-images.githubusercontent.com/20448157/153851807-790c2827-0412-4eff-ba3e-9c4d89c1fd73.png)

Since the update to Laravel 9, I get this error. Is this something that can be solved, or is it better to work around it by calling another function?

```php
/**
 * Get a list of user favorites
 */
public static function getFavorites()
{
    if (Auth::check()) {
        $spotter = Auth::user()->getFavoriteItems(Parkinglocation::class)->get();
        $garage = Auth::user()->getFavoriteItems(Parkinggarage::class)->get();
        $city = Auth::user()->getFavoriteItems(Parkingcity::class)->get();
        $favorites = $spotter->merge($garage)->merge($city);
    } else {
        $favorites = [];
    }
    return $favorites;
}
```

**Comment by haq** [comment]
> ![image](https://user-images.githubusercontent.com/20448157/153851807-790c2827-0412-4eff-ba3e-9c4d89c1fd73.png)
> 
> Since the update to Laravel 9, I get this error. Is this something that can be solved, or is it better to work around it by calling another function?
> 
> ```
> /**
>  * Get a list of user favorites
>  */
> public static function getFavorites()
> {
>     if (Auth::check()) {
>         $spotter = Auth::user()->getFavoriteItems(Parkinglocation::class)->get();
>         $garage = Auth::user()->getFavoriteItems(Parkinggarage::class)->get();
>         $city = Auth::user()->getFavoriteItems(Parkingcity::class)->get();
>         $favorites = $spotter->merge($garage)->merge($city);
>     } else {
>         $favorites = [];
>     }
>     return $favorites;
> }
> ```

Same issue, were you able to figure out a solution?

**Comment by overtrue** [comment]
https://github.com/overtrue/laravel-favorite/releases/tag/5.0.1
