### ISSUE TITLE
Add support for laravel `^6.0|^7.0|^8.0|^9.0` versions

### ISSUE THREAD

**Issue by ahmed-aliraqi** [overtrue/laravel-favorite#30]
Thanks for a great work,
I think this package can be compatible with older versions of Laravel as well. You can update `composer.json` to be compatible with `^6.0|^7.0|^8.0|^9.0` versions.
You should not rely entirely on Laravel Shift https://github.com/overtrue/laravel-favorite/pull/23

**Comment by overtrue** [comment]
@ahmed-aliraqi You can use the old versions of this package to compatible Laravel 6.x,7.x:

overtrue/laravel-favorite: 2.x -> Laravel ^5.5||~6.0||~7.0||~8.0
overtrue/laravel-favorite: 3.x -> Laravel ^7.0|^8.0

Perhaps this package would be compatible with all versions of Laravel, but each major version of the framework has breaking changes, such as the minimum PHP version required. If I were to be compatible with all of these versions, I would have to give up using the new features added to PHP 8, so I chose to use a different package version to support each version of the framework.

PS: PHP 7.4 was not actively supported 7 months ago.  https://www.php.net/supported-versions.php
