### ISSUE TITLE
LengthAwarePaginator breaks when calling attachFavoriteStatus

### ISSUE THREAD

**Issue by boonstoppel** [overtrue/laravel-favorite#33]
$posts = Post::paginate(20);
$postsWithFavoriteStatus = $user->attachFavoriteStatus($posts);

@if (method_exists($postsWithFavoriteStatus, 'links')) // This is always false
      {{ $postsWithFavoriteStatus->links() }}
@endif

**Comment by overtrue** [comment]
@boonstoppel Hi, please upgrade to https://github.com/overtrue/laravel-favorite/releases/tag/5.0.3 to fix it.

**Comment by boonstoppel** [comment]
Problem 1
    - Root composer.json requires overtrue/laravel-favorite ^5.0.3 ->
satisfiable by overtrue/laravel-favorite[5.0.3].
    - overtrue/laravel-favorite 5.0.3 requires laravel/framework ^7.0|^8.0
-> found laravel/framework[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but
it conflicts with your root composer.json require (^9.3).
