### ISSUE TITLE
Why not add support to Laravel 9?

### ISSUE THREAD

**Issue by ssheduardo** [overtrue/laravel-favorite#34]
Hi, I see the last support for Laravel 8, but why not add to Laravel9?

Thanks for the package.

**Comment by overtrue** [comment]
@ssheduardo I made a mistake. I committed an error version from my other computer, I've released a new version [5.0.4](https://github.com/overtrue/laravel-favorite/releases/tag/5.0.4) to fix it. 

Thank you.
