### ISSUE TITLE
Can the user model be Favoriter AND Favoriteable?

### ISSUE THREAD

**Issue by patryyyck** [overtrue/laravel-favorite#35]
Hi,

I'd like to choose users as favorites users.
So, the user model have to use the trait Favoriter and Favoriteable.

Is it possible?
And how?  ;-)

Regards

**Comment by overtrue** [comment]
Hi @patryyyck maybe you need this package? https://github.com/overtrue/laravel-follow

**Comment by patryyyck** [comment]
Very good idea! ;-)
Thanks @overtrue !

**Comment by Hesesses** [comment]
I am having the same problem.

I would like to have favorite users also in favorites list to be able to access those quickly
