### ISSUE TITLE
Latest version not on Packagist?

### ISSUE THREAD

**Issue by klaasnicolaas** [overtrue/laravel-favorite#36]
Is it true that people cannot use the latest version (5.1.0) because it is not yet on [Packagist](https://packagist.org/packages/overtrue/laravel-favorite)?
Because of the upgrade to Laravel 10, I'm stuck updating the package in my project

**Comment by paulelpidorou** [comment]
I am running into the same issue @klaasnicolaas .. seems that version 5.1 is not yet available on Packagist.. @overtrue any update on this?

**Comment by overtrue** [comment]
@klaasnicolaas @paulelpidorou Thanks, I have fixed it.
