### ISSUE TITLE
Access Favorite created_at

### ISSUE THREAD

**Issue by ingageco** [overtrue/laravel-favorite#44]
Thank you for this great package! I was wondering the simplest way of getting the created_at date on the following query

`$favorites = $user->getFavoriteItems(Media::class)->latest()->paginate();`

In this example, I get the Media model, but none of the information on the favorite item. 

I appreciate any input!

**Comment by overtrue** [comment]
take a try:
```php
$user->favorites()->where('favoriteable_type', (new Media)->getMorphClass())->paginate();
```

**Comment by ingageco** [comment]
@overtrue Awesome! Will try it out.

**Comment by ingageco** [comment]
Worked like a charm! (sorry for the delayed response)
