### ISSUE TITLE
Favourite VS Like

### ISSUE THREAD

**Issue by IsraelOrtuno** [overtrue/laravel-favorite#5]
Could you please describe the differences between this package and `like` package? Do not really get it

**Comment by overtrue** [comment]
The name is different, some people like to call it “Like”, some products are called “favorite”, suitable for obsessive-compulsive disorder 😆

**Comment by IsraelOrtuno** [comment]
So basically the same but naming right?

**Comment by overtrue** [comment]
If you have any suggestions, please point out, because I am not good at English, it is inevitable that there may be some incorrect names, Thanks.

**Comment by IsraelOrtuno** [comment]
Yeah the naming is correct, but since functionality for `favourites` `likes` and `bookmark` will likely be the same... I thought that maintaining 3 packages with the same features but different naming would be hard. Just wanted to make sure I was using the right package..
