### ISSUE TITLE
How to show all favorite item based on user

### ISSUE THREAD

**Issue by hasan-almujtaba** [overtrue/laravel-favorite#6]
I have to show all user favorite item based on user logged in, can i do this?

**Comment by chethiya44** [comment]
yes you can

**Comment by overtrue** [comment]
https://github.com/overtrue/laravel-favorite#get-favorite-model-from-user

<blockquote><img src="https://avatars1.githubusercontent.com/u/1472352?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/overtrue/laravel-favorite">overtrue/laravel-favorite</a></strong></div><div>:heart: User favorite feature for Laravel Application. - overtrue/laravel-favorite</div></blockquote>

**Comment by Hesesses** [comment]
Hi and thank you for creating this. I was also wondering how to get ALL favorites as models.

for example $user->favorites will return array of:
```
[
    "id" => 18
    "user_id" => 3031
    "favoriteable_type" => "App\Models\Event"
    "favoriteable_id" => 409
    "created_at" => "2023-10-04 11:20:25"
    "updated_at" => "2023-10-04 11:20:25"
  ]
  ```
  
  Would be nice to get array of actual models

**Comment by overtrue** [comment]
>  $user->favorites 

This isn't an array, it's a collection of models.  

```
dd($user->favorites)
```

**Comment by Hesesses** [comment]
Thank you for super fast reply!

<img width="721" alt="image" src="https://github.com/overtrue/laravel-favorite/assets/2721970/c321799a-606d-42e9-a886-e4b357fb3e67">

I got this sorted by doing this:
`$favorites = $user->load('favorites.favoriteable')->favorites;`
